### ISSUE TITLE
Speicherfunktion

### ISSUE THREAD

**Issue by Kepplinger** [htl-leonding/2016_3CHIF_OnTopCalc#2]
Implementieren einer Speicherfunktion während der Bearbeitung eines Projekts. Bei nicht gespeicherten Änderungen soll bei dem jeweiligen Tab ein \* erscheinen.

**Comment by Schausi** [comment]
Muss ich jetzt wirklich für jedes Element den listener adden oder gibt es auch die möglichkeit einen listerner für einpane zu adden. ich finde nur swing tutorials hat jemand eine idee ob das geht und mit welchem listener?

**Comment by ThomasStuetz** [comment]
ev. hilft das
http://stackoverflow.com/questions/18597939/javafx-handle-mouse-event-anywhere
http://docs.oracle.com/javafx/2/events/filters.htm

**Comment by Schausi** [comment]
Dankeschön, hat geholfen.
